# Generated by Django 3.1.2 on 2020-10-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripskip', '0002_complaintmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
