# Generated by Django 3.1.2 on 2020-10-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripskip', '0004_complaintmessage_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightOrderBooked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('amount', models.CharField(default='', max_length=50)),
                ('payment_id', models.CharField(default='', max_length=100)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
