# Generated by Django 3.1.2 on 2020-10-14 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripskip', '0006_flightorderbooked_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightorderbooked',
            name='order_id',
        ),
    ]
