# Generated by Django 3.1.2 on 2020-10-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripskip', '0007_remove_flightorderbooked_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightorderbooked',
            name='AdultName',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='flightorderbooked',
            name='ArrivalPlace',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='flightorderbooked',
            name='ArrivalTime',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='flightorderbooked',
            name='ChildName',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='flightorderbooked',
            name='DeparturePlace',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='flightorderbooked',
            name='DepartureTime',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='flightorderbooked',
            name='FlightDate',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='flightorderbooked',
            name='FlightNum',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='flightorderbooked',
            name='InfantName',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='flightorderbooked',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='flightorderbooked',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
