# Generated by Django 3.1.2 on 2020-10-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripskip', '0008_auto_20201014_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelOrderBooked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('amount', models.CharField(default='', max_length=50)),
                ('payment_id', models.CharField(default='', max_length=100)),
                ('tRoom', models.CharField(default='', max_length=50)),
                ('tAdults', models.CharField(default='', max_length=50)),
                ('tChild', models.CharField(default='', max_length=50)),
                ('HotelName', models.CharField(default='', max_length=50)),
                ('checkIn', models.CharField(default='', max_length=50)),
                ('checkOut', models.CharField(default='', max_length=50)),
                ('FirstName', models.CharField(default='', max_length=50)),
                ('LastName', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
