# Generated by Django 3.1.2 on 2020-10-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripskip', '0009_hotelorderbooked'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelorderbooked',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
